spring:
  datasource:
    username: mafia_user
    password: mafia_pass
    url: jdbc:postgresql://185.246.65.132:5433/mafia
  jpa:
    properties:
      hibernate:
#        generate_statistics: true
    show-sql: true